name: AI Code Review

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@8bd66227f057f21e847a8c27c9b356c25271d292
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Chinese
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo
          MAX_TOKENS: 4096
          MAX_PATCH_LENGTH: 10000
